name: price_predictor
language: python
variables:
  - name: COMET_ML_API_KEY
    inputType: Secret
    description: ''
    defaultValue: COMET_ML_API_KEY
    required: true
dockerfile: Dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
