name: trade_to_ohlc
language: python
variables:
  - name: KAFKA_INPUT_TOPIC
    inputType: InputTopic
    description: This is the kafka topic from which we will read trades
    defaultValue: trades_live
    required: true
  - name: KAFKA_OUTPUT_TOPIC
    inputType: OutputTopic
    description: this is the kafka topic where we will save the ohlc candles
    defaultValue: ohlc_live
    required: true
  - name: KAFKA_CONSUMER_GROUP
    inputType: FreeText
    description: This is the consumer group that we will use to read trades from the input topic
    defaultValue: trade_to_ohlc_live_consumer_group
    required: true
dockerfile: Dockerfile
runEntryPoint: src/main.py
defaultFile: src/main.py
